functionsDirectory = "C:\\Users\\miguell\\inventory-war\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\miguell\\inventory-war"
publishOrigin = "config"
functions = "C:\\Users\\miguell\\inventory-war\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/data"
to = "/.netlify/functions/data"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/smart-suggest"
to = "/.netlify/functions/smart-suggest"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/asana-task"
to = "/.netlify/functions/asana-task"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/asana-tasks"
to = "/.netlify/functions/asana-tasks"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/five-whys"
to = "/.netlify/functions/five-whys"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/monday-gantt"
to = "/.netlify/functions/monday-gantt"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/asana-comment"
to = "/.netlify/functions/asana-comment"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]